"""Properties that must hold for any sentence at all.

Every bug found by hand in this parser was an invariant violation, not a wrong
answer to a known question: a stated 800 m coming back as 600, a bike ride
defaulting to a runner's distance, a named city dropped because the sentence
also said "centro". None of those needed a model to notice — only a rule
saying what must never happen, and enough sentences to trip over it.

So the corpus is generated by a model once (tools/make_sentences.py) and the
checking is deterministic. No API key, no network, no per-run cost, and it
fails loudly the moment a change breaks something nobody thought to test.
"""
import io
import os
import re

import pytest

from backend import config, intent
from backend.intent import RIDE_SIZES, normalise, read, read_detailed, stated_climb, summarise

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")

# Two corpora, doing different jobs. The generated one is breadth — phrasings
# nobody thought of. The hand-written one is depth — every line is a bug that
# was actually hit. Breadth alone is not enough: the generated file holds five
# "fuori citta" sentences and none of the one that matters, because only
# "stare fuori citta" trips the pattern the negation guard exists to stop.
def _corpus(name):
    with io.open(os.path.join(FIXTURES, name), encoding="utf-8") as handle:
        return [
            line.strip() for line in handle
            if line.strip() and not line.startswith("#")
        ]


CORPUS = _corpus("sentences.txt") + _corpus("adversarial.txt")


def test_the_corpus_is_actually_varied():
    """A guard on the fixture itself: a corpus that all looks the same would
    pass every property below while testing nothing."""
    assert len(CORPUS) >= 80
    parsed = [read(s) for s in CORPUS]
    assert len({p.sport for p in parsed}) > 1
    assert sum(1 for p in parsed if p.distance_km) > 15
    assert sum(1 for p in parsed if p.start_text) > 15
    assert sum(1 for p in parsed if p.elevation_gain_m) > 15


@pytest.mark.parametrize("sentence", CORPUS)
def test_reading_a_sentence_never_raises(sentence):
    read_detailed(sentence)
    summarise(read(sentence), "it")
    summarise(read(sentence), "en")


@pytest.mark.parametrize("sentence", CORPUS)
def test_reading_is_stable(sentence):
    """Same input, same answer. A parser that drifts cannot be cached, and
    every answer here is cached."""
    assert read(sentence).model_dump() == read(sentence).model_dump()


@pytest.mark.parametrize("sentence", CORPUS)
def test_case_and_accents_do_not_change_the_reading(sentence):
    """Normalisation folds these, and the cache key depends on it: if they
    parsed differently, two spellings of one sentence would be two answers."""
    assert read(sentence).model_dump() == read(sentence.upper()).model_dump()


@pytest.mark.parametrize("sentence", CORPUS)
def test_every_value_read_is_within_its_own_bounds(sentence):
    parsed = read(sentence)
    if parsed.distance_km is not None:
        assert 0.5 < parsed.distance_km <= 200
    if parsed.elevation_gain_m is not None:
        assert 0 <= parsed.elevation_gain_m <= 6000
    if parsed.calories is not None:
        assert 50 <= parsed.calories <= 10000
    if parsed.mass_kg is not None:
        assert 30 <= parsed.mass_kg <= 250
    for field in ("sport", "mode", "surface", "sights", "area"):
        value = getattr(parsed, field)
        if value is not None:
            assert value in {
                "sport": config.SPORTS, "mode": config.MODES,
                "surface": config.SURFACE_PREFERENCES, "sights": config.SIGHTS,
                "area": config.AREAS,
            }[field]


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_stated_climb_is_the_climb_that_comes_back(sentence):
    """"con 800mt di dislivello" once came back as the generic hilly tier,
    silently replacing a number somebody typed with a guess."""
    if not stated_climb(sentence):
        return
    written = intent._numeric_climb(normalise(sentence))
    assert read(sentence).elevation_gain_m == written


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_stated_climb_is_shown_back_as_that_number(sentence):
    parsed = read(sentence)
    if not stated_climb(sentence) or parsed.elevation_gain_m is None:
        return
    said = " ".join(summarise(parsed, "it", exact_climb=True))
    assert "{:.0f} m".format(parsed.elevation_gain_m) in said


@pytest.mark.parametrize("sentence", CORPUS)
def test_an_inferred_distance_suits_the_sport(sentence):
    """A five kilometre bike ride is not a bike ride. Only checks distances we
    chose: a person asking for 3 km on a bike gets 3 km."""
    parsed, guessed = read_detailed(sentence)
    if not guessed or parsed.sport != "cycling" or parsed.distance_km is None:
        return
    assert parsed.distance_km >= RIDE_SIZES["cycling"]["normal"]["small"][0]


@pytest.mark.parametrize("sentence", CORPUS)
def test_wanting_out_of_town_never_reads_as_wanting_to_stay(sentence):
    """"fuori citta" contains "citta" — the trap that has bitten three times."""
    text = normalise(sentence)
    if not re.search(r"\bfuori\s+citt|\bout\s+of\s+(?:the\s+)?town|\bcountryside\b", text):
        return
    assert read(sentence).area is None


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_place_that_is_read_is_a_place_that_is_shown(sentence):
    """Anything acted on has to appear in the chips, or the reader cannot tell
    what was understood before spending a search on it."""
    parsed = read(sentence)
    said = " ".join(summarise(parsed, "it")).lower()
    if parsed.start_text:
        assert parsed.start_text.lower() in said
    if parsed.end_text:
        assert parsed.end_text.lower() in said


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_place_is_never_a_word_that_means_nowhere(sentence):
    """A generic noun geocodes to something real and far away — "the park" is
    a pub in Norfolk — so the search would run somewhere nobody named."""
    parsed = read(sentence)
    for text in (parsed.start_text, parsed.end_text):
        if text is None:
            continue
        assert len(text) >= 3
        assert text not in intent.NOT_A_PLACE
        assert not text.startswith(("il ", "la ", "the ", "un ", "una "))


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_destination_means_a_route_and_no_destination_means_a_loop(sentence):
    parsed = read(sentence)
    if parsed.end_text:
        assert parsed.mode == "route"
    if parsed.mode == "loop":
        assert parsed.end_text is None


@pytest.mark.parametrize("sentence", CORPUS)
def test_a_sentence_giving_nothing_is_thin_enough_to_ask_about(sentence):
    """The model is only worth paying for when the rules came back with
    nothing to act on — and it must be asked whenever they did."""
    parsed, guessed = read_detailed(sentence)
    if parsed.distance_km is None and not parsed.start_text:
        assert intent.is_thin(parsed, guessed) is True
