"""Generate a corpus of plausible sentences, once, and keep it.

The expensive part of testing a natural-language reader is imagining what
people will type. That is worth a model call. Deciding whether the answer is
right is not: the properties in tests/test_sentence_properties.py are
deterministic Python and cost nothing to run a thousand times.

So this runs rarely — by hand, when the corpus feels thin — writes a file, and
that file is what the suite reads from then on. One call, a couple of cents,
and no API in the test path at all.

    ./.venv/bin/python -m tools.make_sentences            # only if missing
    ./.venv/bin/python -m tools.make_sentences --force    # regenerate
"""
from __future__ import annotations

import argparse
import io
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)

OUT = os.path.join(_ROOT, "tests", "fixtures", "sentences.txt")

# Deliberately asks for the awkward ones. A corpus of well-formed requests
# tests the happy path, which is not where any of this breaks.
PROMPT = """You are helping test a route-search app for runners and cyclists.
It takes a sentence like "voglio correre 10 km senza troppo dislivello".

Write {count} DIFFERENT sentences someone might really type. Cover:
- Italian and English, roughly half each
- running and cycling
- with and without a distance; with and without a climb figure
- named places (Italian cities, districts, landmarks) and no place at all
- durations instead of distances ("un'ora", "half an hour")
- calorie targets
- vague requests with almost no information
- staying in town, in the centro storico, and getting out of town
- typos, missing accents, lowercase, run-on phrasing
- awkward ones: "intorno a", "lungo il fiume", "fuori citta", "non sono allenato"

One sentence per line. No numbering, no quotes, no commentary."""


def generate(count: int) -> list:
    import anthropic

    client = anthropic.Anthropic()
    response = client.messages.create(
        model=os.environ.get("INTENT_MODEL", "claude-haiku-4-5"),
        max_tokens=8000,
        messages=[{"role": "user", "content": PROMPT.format(count=count)}],
    )
    text = "".join(
        block.text for block in response.content if getattr(block, "type", "") == "text"
    )
    lines = []
    for line in text.splitlines():
        line = line.strip().strip('"').strip()
        # A model asked for a list will sometimes number it anyway.
        while line[:1].isdigit() or line[:1] in ".-)":
            line = line[1:].lstrip()
        if 8 <= len(line) <= 200:
            lines.append(line)
    usage = response.usage
    print("{} in, {} out tokens".format(usage.input_tokens, usage.output_tokens))
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=140)
    parser.add_argument("--force", action="store_true",
                        help="regenerate even though the file exists")
    args = parser.parse_args()

    if os.path.exists(OUT) and not args.force:
        print("{} already exists; --force to regenerate".format(OUT))
        return

    lines = generate(args.count)
    if len(lines) < args.count // 2:
        raise SystemExit("only got {} usable lines; not overwriting".format(len(lines)))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8") as handle:
        handle.write("# Generated by tools/make_sentences.py. Checked in on purpose:\n")
        handle.write("# the tests must not need an API key, or they will not run.\n")
        for line in lines:
            handle.write(line + "\n")
    print("wrote {} sentences to {}".format(len(lines), OUT))


if __name__ == "__main__":
    main()
